[workspace]
resolver = "2"
members = [
  "core",
  "bindings/c",
  "bindings/wasm",
  "libsql-sys",
  "libsql-shell",
  "wasmtime-bindings",
]

[profile.release]
codegen-units = 1
panic = "abort"

[patch.crates-io]
sqlite3-parser = { git = "https://github.com/LucioFranco/lemon-rs" }
